services:
  - type: web
    name: care-doc-demo
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py"  # or whatever your app's main file is
    runtime: python-3.11
